version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo node version check
            - node -v
            - npm -v
            - npm install -g aws-cdk
            - npm install -g sst@latest
    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - echo "Dependencies installed"
    build:
        commands:
            - echo Build started on `date`
            - npx sst deploy --stage production --verbose --no-cache
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
