version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20
        commands:
            - echo node version check
            - node -v
            - npm -v
            - npm install -g aws-cdk
            - npm install -g sst@3.3.3
    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - rm -rf .next
            - npm install
            - echo "Dependencies installed"
    build:
        commands:
            - echo Build started on `date`
            - npx sst deploy --stage production
    post_build:
        commands:
            - echo Build completed on `date`
            - echo "Manually copying BUILD_ID file"
            - if [ -f ".next/BUILD_ID" ]; then cp .next/BUILD_ID .open-next/assets/BUILD_ID; else echo "BUILD_ID not found"; fi
artifacts:
    files:
        - '**/*'
