version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20
        commands:
            - echo node version check
            - node -v
            - npm -v
            - npm install -g aws-cdk
            - npm install -g sst@latest
    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - export DEBUG="*"
            - export AWS_REGION=ap-northeast-2
            - export SST_STAGE=production
            - npx sst deploy --stage production
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
