import './globals.css';
import type { Metadata } from 'next';
import { Modals } from '@/components/common/Modal';
import Footer from '@/components/layout/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko">
            <body>
                <div className="rootLayout">
                    <main className="main">{children}</main>
                    <div className="footer">
                        <Footer />
                    </div>

                    <Modals />
                </div>
            </body>
        </html>
    );
}
