import './globals.css';
import type { Metadata } from 'next';
import { Modals } from '@/components/common/Modal';
import ConditionalLayout from '@/components/layout/\bConditionalLayout';
import AuthProvider from '@/shared/context/AuthProvider';
import QueryProvider from '@/shared/context/QueryProvider';

export const metadata: Metadata = {
    title: 'Eat-Fit',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ko">
            <body>
                <QueryProvider>
                    <AuthProvider>
                        <ConditionalLayout>{children}</ConditionalLayout>
                    </AuthProvider>
                </QueryProvider>
                <Modals />
            </body>
        </html>
    );
}
